algoritmo "ex1"
// Função : Desenvolva um algoritmo que receba dois números
//          e mostre o maior.
// Autor : Anton L. Mazon R. Rangel
// Data : 10/03/2015
// Seção de Declarações
var
   x,y:real
inicio
   escreva("Digite um numero: ")
   leia(x)
   escreva("Digite outro numero: ")
   leia(y)

   se (x > y) entao
      escreval("O maior é ", x)
   senao
      escreval("O maior é ", y)
   fimse
fimalgoritmo
