algoritmo "ex7"
// Função : Faça um algoritmo que receba um número
//          inteiro e verifique se é par ou ímpar.
// Autor : Anton L. Mazon R. Rangel
// Data : 10/03/2015
// Seção de Declarações 
var
    n:inteiro
inicio
      escreva("Digite um numero: ")
      leia(n)
      
      se (n % 2 = 0) entao
         escreval(n, " é par!")
      senao
         escreval(n, " é impar!")
      fimse
fimalgoritmo
