algoritmo "ex11"
// Função : Faça um programa que converta temperaturas em graus
//          Celsius(ºC) para graus Fahrenheit(ºF). A formula
//          de conversao é dada por:
//          F = 9C + 160 / 5
// Autor : Anton L. Mazon R. Rangel
// Data : 11/03/2015
// Seção de Declarações
var
   c:real
inicio
      escreva("Temperatura em ºC: ")
      leia(c)
      
      escreval()
      escreval("Temperatura em ºF: ", (9*c+160)/5)
fimalgoritmo
