algoritmo "ex2"
// Função : Faça um programa que receba tres notas, calcule e mostre
//          a média aritmetica entre elas.
// Autor : Anton L. Mazon R. Rangel
// Data : 11/03/2015
// Seção de Declarações
var
   n1,n2,n3:real
inicio
      escreva("Digite a 1ª nota: ")
      leia(n1)
      escreva("Digite a 2ª nota: ")
      leia(n2)
      escreva("Digite a 3ª nota: ")
      leia(n3)
      
      escreval()
      escreval("Média: ", (n1+n2+n3)/3)
fimalgoritmo
