algoritmo "ex4"
// Função : Faça um programa que receba o salario de um funcionario,
//          calcule e mostre o novo salario, sabendo-se que este sofreu
//          um aumento de 25%.
// Autor : Anton L. Mazon R. Rangel
// Data : 11/03/2015
// Seção de Declarações
var
   sal:real
inicio
      escreva("Salario: ")
      leia(sal)
      
      escreval()
      escreval("Salario com reajuste de 25%: ", sal+(sal*0.25))
fimalgoritmo
