algoritmo "ex9"
// Função : Faça um programa que calcule e mostre a area de um triangulo
//          Sabe-se que: Area = (base * altura)/2
// Autor : Anton L. Mazon R. Rangel
// Data : 11/03/2015
// Seção de Declarações
var
   b,h:real
inicio
      escreva("Base  :")
      leia(b)
      escreva("Altura:")
      leia(h)
      
      escreval()
      escreval("Area : ", (b*h)/2)
fimalgoritmo
