algoritmo "ex2"
// Função : Escreva um algoritmo que por meio de atribuição,
//          a variável msg receba o seguinte conteúdo:
//          “Algoritmo só se aprende fazendo!”.
//           Exiba o conteúdo armazenado na variável msg.
// Autor : Anton L. Mazon R. Rangel
// Data : 10/03/2015
// Seção de Declarações
var
   msg:caracter
inicio
      msg <- "Algoritmo só se aprende fazendo!"
      escreval(msg)
fimalgoritmo
