algoritmo "ex7"
// Função : Escreva um algoritmo que calcule a área de um triangulo:
//          Fórmula: area = (b * h)/2, sendo b a base e h a altura.
// Autor : Anton L. Mazon R. Rangel
// Data : 10/03/2015
// Seção de Declarações
var
   b,h:real
inicio
      escreva("Base  : ")
      leia(b)
      escreva("Altura: ")
      leia(h)
      escreval("Área do triângulo: ", (b*h)/2)
fimalgoritmo
