algoritmo "ex13"
// Função : Faça um algoritmo que leia uma temperatura em graus
//          Centígrados (C) e apresente a temperatura em Fahrenheit (F).
//          A fórmula é a seguinte:
//          Fórmula: F=(9*C+160)/5
// Autor : Anton L. Mazon R. Rangel
// Data : 10/03/2015
// Seção de Declarações
var
   c:real
inicio
      escreva("Digite temperatura em ºC: ")
      leia(c)
      
      escreval("Temperatura em ºF: ", (9*c+160)/5)
fimalgoritmo
