algoritmo "ex15"
// Função : Desenvolva um algoritmo que receba o salário de um
//          funcionário, calcule e mostre o novo salário,
//          sabendo-se que este sofreu um aumento de 25%.
// Autor : Anton L. Mazon R. Rangel
// Data : 10/03/2015
// Seção de Declarações
var
   s:real
inicio
      escreva("Salário: ")
      leia(s)
      
      escreval()
      escreval("Salário com aumento de 25%  : R$", s+(s*0.25))
fimalgoritmo
