algoritmo "ex2"
// Função : Escreva um algoritmo que por meio de atribuição,
//          a variável msg receba a seguinte sequencia de caracteres:
//          “Algoritmo só se aprende fazendo!”.
//          Exiba o conteúdo armazenado na variável msg.
// Autor : Anton L. Mazon R. Rangel
// Data : 24/02/2015
// Seção de Declarações 
var
   msg:caracter
inicio
      msg <- "Algoritmo só se aprende fazendo!"
      escreva(msg)
fimalgoritmo
