algoritmo "ex3"
// Função : Escreva um algoritmo que leia a temperatura
//          em centígrados e a apresente em garus Fahrenheit.
//          Fórmula: F = (9.c + 160)/5
// Autor : Anton L. Mazon R. Rangel
// Data : 24/02/2015
// Seção de Declarações
var
   c:real
inicio
      escreva("Temperatura em ºC: ")
      leia(c)
      escreva("Temperatura em ºF: ")
      escreva( (9*c + 160)/5 )
fimalgoritmo
