algoritmo "ex8"
// Função : Escreva um algoritmo que calcule a área de um triangulo:
//          Fórmula: area = (b x h)/2, sendo b a base e h a altura.
// Autor : Anton L. Mazon R. Rangel
// Data : 24/02/2015
// Seção de Declarações
var
   b,h:numerico
inicio
      escreva("Digite o tamanho da BASE  : ")
      leia(b)
      escreva("Digite o tamanho da ALTURA: ")
      leia(h)
      
      escreva("A ÀREA do triângulo é     : ")
      escreva( (b * h) / 2 )
fimalgoritmo
