algoritmo "ex1"
// Função : Faça um algoritmo que leia a idade
//          e informe se o individuo é 'de maior ou não".
// Autor : Anton L. Mazon R. Rangel
// Data : 04/03/2015
// Seção de Declarações
var
   idade:inteiro
inicio
      escreva("Digite a idade: ")
      leia(idade)
      
      se (idade >= 18) entao
         escreva("É de maior!")
      senao
         escreva("Não é de maior!")
      fimse
fimalgoritmo
